# TbD net arguments (pass to constructor)
image_feature_size: [1024, 14, 14]
module_channels: 128
class_projection_channels: 1024
classifier_linear_size: 1024

# optimization related arguments
num_iterations: 20000
weight_decay: 0.000
batch_size: 512

### learning rate scheduling - (lr *= gamma)
### We don't do it for NMN training.
initial_lr: 0.0004
lr_gamma: 1
lr_steps: [100000]

### module training: program generator checkpoint
pg_checkpoint: "checkpoints/program_generator_best.pth"
pg_embedding_size: 128
pg_rnn_hidden_size: 64
pg_rnn_dropout: 0.0
