# Arguments for the constructor of NeuralModuleNetwork model
model_image_feature_size: [1024, 14, 14]
model_module_channels: 128
model_class_projection_channels: 1024
model_classifier_linear_size: 1024

# Optimization arguments (adam optimizer by default)
optim_num_iterations: 35000
optim_batch_size: 128
optim_weight_decay: 0.000

### Learning rate scheduling - (lr *= gamma) if answer accuracy plateaus
optim_lr_initial: 0.0001
optim_lr_gamma: 0.9
optim_lr_patience: 10000
### No LR scheduling here.

# Arguments for the constructor of ProgramGenerator model
pg_checkpoint: "data/program_generator_best_checkpoint.pth"
pg_input_size: 256
pg_hidden_size: 256
pg_num_layers: 2
pg_dropout: 0.0
