RANDOM_SEED: 0
PHASE: program_prior

# Arguments for the constructor of ProgramPrior model.
PROGRAM_PRIOR:
  INPUT_SIZE: 256
  HIDDEN_SIZE: 256
  NUM_LAYERS: 2
  DROPOUT: 0.0

# Optimization arguments, we use Adam optimizer and ReduceLROnPlateau scheduler.
OPTIM:
  BATCH_SIZE: 256
  NUM_ITERATIONS: 20000
  WEIGHT_DECAY: 0.0

  # Learning rate scheduling: (lr *= gamma) if perplexity plateaus.
  LR_INITIAL: 0.01
  LR_GAMMA: 0.5
  LR_PATIENCE: 3
